### PR TITLE
Updating pointers for RL teams score.

### PR DESCRIPTION
**Pull request by th3an7**
I wasn't quick enough with finding those ones and adding them to my previous commit...

One thing is, I don't know how can I find on which team the player currently is as I don't know what initial value either of the team have.
Will look further... maybe I will find something.

### CODE REVIEW

**Comment by simon-wh** [comment]
Thanks again!

**Comment by busaku** [comment]
did not work :(

**Comment by th3an7** [comment]
@busaku check this https://github.com/antonpup/Aurora/issues/730

**Comment by Jeremiidesu** [comment]
Working on pointers as of today's (March 17, 2018, v1.42) version of the game, will comment the pointer values I found as soon as I am done with them.

**Comment by Jeremiidesu** [comment]
Okay, this works for me:
```json
{
  "Team": {
    "baseAddress": "27130828",
    "pointers": [ "56", "972" ]
  },

  "Orange_score": {
    "baseAddress": "26356988",
    "pointers": [ "1056", "724", "1244", "4", "524" ]
  },

  "Blue_score": {
    "baseAddress": "26356988",
    "pointers": [ "1056", "724", "1244", "0", "524" ]
  },

  "Boost_amount": {
    "baseAddress": "26356972",
    "pointers": [ "76", "64", "988", "1364", "84" ]
  }
}
```

**Comment by simon-wh** [comment]
@Jeremiidesu Do you want to make a pull request with these changes?

**Comment by Jeremiidesu** [comment]
Will do tonight, with additional changes made to the codebase to fix some other rocket league related stuff

**Pull request closed without merging**
