### PR TITLE
 Corsair Peripherals Support (including RAM, Fans, LED Strips), added Shared Mode

### PR DESCRIPTION
**Pull request by Gurjot95**
**List any issues that this PR fixes:** fixes # , etc...
#1419 

**This pull request proposes the following changes:**

-  Adds support for most corsair peripherals such as RAM, Lighing Node, Commander Pro etc which follows mouse color
- Added device option to whether to run SDK in shared mode with iCue and option to disable each peripheral
- Optimized whole corsair device code (needs testing so all corsair devices are working fine)
- Updated SDK, this time for real
- Should fix RAM issue from last PR (thanks @srodriguez1850)
- Fixes Harpoon Mouse issue

**Known issues/To do:**

- Needs extensive testing

### CODE REVIEW

**Comment by zejjnt** [comment]
How can I test this? Since I can find no executable, how do I compile it?

**Comment by diogotr7** [comment]
@zejjnt you have a premade build here https://ci.appveyor.com/project/antonpup/aurora/builds/23648968/artifacts

**Comment by zejjnt** [comment]
Well this is kind of a mixed bag, but there is clearly progress. The mouse pad and keyboard are in excellent sync and that's just awesome.
But from what I've seen, the fan colors are set based only on one single spot; the mouse logo, correct? Because while they do blink every now and then it is always the same color and there is no fading whatsoever, either all fans on or off in the same static color.
I'm guessing you're going to expand on this feature in the future but I still have to point out that color gradients and different fans for different audio frequencies is the ultimate goal, isn't it? :)

Unfortunately my RAM is still doing its default pattern from iCue despite iCue saying that they are controlled via the SDK. My SteelSeries Arctis 5 is not in this equation at all, they are just doing the default rainbow fading.

Great work anyhow :)

**Comment by Axodious** [comment]
For me the fans are responding to my typing fine (in desktop mode).

I did notice a possible major problem, when Aurora is opened the fans disappear from iCue which seems to remove the fan speed control (I think). Woke up this morning with my computer pretty warm, went to iCue and noticed the fans not in the Commander Pro, uninstalled Aurora, rebooted and the fans were back in iCue.

**Comment by zejjnt** [comment]
> For me the fans are responding to my typing fine (in desktop mode).
> 
> I did notice a possible major problem, when Aurora is opened the fans disappear from iCue which seems to remove the fan speed control (I think). Woke up this morning with my computer pretty warm, went to iCue and noticed the fans not in the Commander Pro, uninstalled Aurora, rebooted and the fans were back in iCue.
> 
> _EDIT_
> It looks like it might not be just Aurora causing the fans to stop showing RPM in iCue, a while after the reboot the fans disappeared by themselves. I did notice that if they are there and I start Aurora they disappear right away.
> 
> _EDIT 2_
> I found this post regarding the Commander Pro: http://forum.corsair.com/v3/showthread.php?t=181855#9
> 
> Apparently you can only have 1 connection to it at a time, so when Aurora is taking over it's stopping iCue from monitoring and adjusting any fans plugged in as well. Not sure there's a workaround for Aurora other than adding it's own form of fan speed controls.
> 
> _EDIT 3_
> One workaround is to plug the fan controls directly on the motherboard and only plug the RGB cable into the Commander Pro. Don't have to worry about iCue controlling the fan speed at all this way.

That might explain why iCue often starts on another profile than what it was set to when I shut down my computer maybe.
And about the only one device-thing I noticed something in the Device Manager related to what you are writing;
image
As I have said I have two Lightning Nodes, one Commander Pro, 2 LL-fans, 3 ML-fans and one MM800RGB mouse pad but only the mouse pad is showing.
Meanwhile I have a Logitech mouse (G502) that is not detected, SteelSeries Arctis 5 which are detected but only change color sometimes - and a Razer Chroma Blackwidow v2 which somehow registers as a lot of stuff that it isn't.

I don't know if this is any help to you but I thought why not give the info I have...

**Comment by maestroraymond** [comment]
I will be testing this out with the Lighting Node Pro over the weekend.
Have been flawlessly using Aurora with a Steel Series Rival (flickering aside, workaround: switch preferred device to another mouse), Corsair K70 + some additional devices every now and then.
I'm new to GitHubbing so don't know if it's the right place for these kinds of notes, but hey ho, just my input on the great project that is Aurora:
- Devices could be separated and moved/dragged/swapped to the desired position in the manager (eg. left/right handed mouse users)
- As far as the LightingNode and similar LEDs go, I saw another pull request about Hue+ devices, would it be possible to implement a similar approach? (following the keyboard lighting, or assignable lighting like LedStrip1 copy lighting of f1-f12, LedStrip 2 esc-ctrl)

**Comment by diogotr7** [comment]
@maestroraymond 
The approach of making the light strips follow the keyboard like the nzxt hue PR is most likely possible.

Your idea of dragging devices around the screen is partially working on another branch, so that is the way Aurora is going to work in the future. Also proper support for case lighting and keypads for example is planned along with that change.

Your githubbing is just fine :)

**Comment by maestroraymond** [comment]
Thanks for the kind words @diogotr7.
I'm coming back to coding and I'll start playing with some other repo's as currently the only way to make a node pro work somewhat correctly as 'ambilight' feature (apart from following the mouse or any other pre-set peripherial is syncing/slaving the individual leds to specific keys on the keyboard. I am currently testing this with DarthAffe's RGB.NET/RgbSync+ alongside Aurora.
Will update if that works correctly!

**Comment by Gurjot95** [comment]
@maestroraymond @zejjnt @Axodious 
Guys please check the new PR build #1580 which adds Corsair support using RGB.NET. Let me know in that thread if it works!

**Comment by Axodious** [comment]
I'm away for a week I'll check when I get back.

**Comment by zejjnt** [comment]
NOW we're talking! Everything lights up now, SteelSeries, Corsair and Razer correctly and in sync. I think the SteelSeries are still controlled by Engine but it works anyway (just without automatically matching colors).
The fans only light up in one color but that is more than enough to impress, it's quite fluent when you set "Fine" instead of "Best".
Great work people! <3

**Comment by Gurjot95** [comment]
Great, please any more updates in #1580 thread as I am closing this for now. Thanks!

**Pull request closed without merging**
