### PR TITLE
Nordic localization for Logitech G910v2

### PR DESCRIPTION
**Pull request by kaporten**
Related to https://github.com/antonpup/Aurora/issues/523

I've added required "Nordic" localization files (Should cover Denmark, Sweden and Norway), and verified that all keys now light up as clicked using a simple Interactive Layer with Key Fade events on the Logitech G910v2.

**Remaining issues**
Only troublesome keys left are RETURN/ENTER which always lights up on the primary board, even if clicked on the numpad, but I read somewhere that this was not something that could be fixed, due to both keys being reported as the same keycode value.

A similar issue affects "minus" on the Nordic layout -- the key just to the left of the RSHIFT button. This is a minus symbol on Nordic layouts, and has the same effect as clicking minus on the numpad.

### CODE REVIEW

**Comment by antonpup** [comment]
Thank you for your contribution. At a first glance, it looks well implemented. But unfortunately, I am busy, and will only be able to slowly begin working on Aurora sometime in next two weeks. So, my apologies in advance for a delay.

**Comment by kaporten** [comment]
No rush, just happy to contribute with localization.

By the way - I feel there is missing some similar localization in "ToLogitechBitmap.ToLogitechBitmap", but the code there wasn't in use by the single use-case (key highlight) I knew how to test.

If you let me know how to test out that class as well, I can do a similar update there.

**Comment by magnus97** [comment]
Spotted a flaw that the - key right next to . does not activate the right key fix for this is to change line 247: return DeviceKeys.NUM_MINUS; to return DeviceKeys.FORWARD_SLASH;

**Comment by kaporten** [comment]
You're right - the OemMinus key next to . did not highlight, but instead the minus on numpad did. I thought that was just due to same keycode being sent (as with the 2 Enter keys sending same keycode), but it wasn't. Thanks.

**Comment by antonpup** [comment]
This is specifically for G910v2? Would this be functional with G910v1 or any other Logitech keyboard for that matter?

I would have to also make these changes for other supported brands.

**Comment by kaporten** [comment]
No I don't think this is specific to any one keyboard -- the title was just from me discovering the issue on this board. After investigating and performing the code changes, I've not had to change any Logitech-specific files at all.

Only generic files such as KeyUtils and KeyboardLayoutManager.

I've only tested these changes on a Logitech G910v2 (only Aurora-compatible board I own), but I expect these changes to be appliccable to any Nordic-layout board.

**Comment by antonpup** [comment]
I see that this PR is from master to master. Could you please redo it for dev branch, so I can include it in development.

**Comment by kaporten** [comment]
Yes, sure - closing this PR

**Pull request closed without merging**
