### PR TITLE
CoolerMaster Masterkeys Pro M and Masterkeys Pro S White support

### LINKED ISSUE #603: Masterkeys Pro M Support
Are there plans to add support for the CoolerMaster Masterkeys Pro M RGB model? I see that the L and S are already supported, and they use the same SDK.

### PR DESCRIPTION
**Pull request by brainbug89**
**List any issues that this PR fixes:**

Fixes #603 

**This pull request proposes the following changes:**

- added latest CoolerMaster SDKDLL.dll
- added Masterkeys Pro M and Masterkeys Pro S White to CoolerMasterSDK

**Known issues/To do:**

- Keyboard layout for Masterkeys Pro M needs to be added to Aurora

### CODE REVIEW

**Comment by simon-wh** [comment]
Thanks for the contribution!

**Comment by EdwardChamberlain** [comment]
I seen to be having some difficulty getting this to work with the Masterkeys Pro M. When I open Aurora The RGB goes off but I dont seem to be able to apply any effects to the KB - mouse seems to work fine (Logitech G502)

**Comment by brainbug89** [comment]
Are you using the latest dev version?

**Comment by EdwardChamberlain** [comment]
Yes - 0.6.1-Dev3.

**Comment by brainbug89** [comment]
Can you post your log file? You can find the logs here: `%appdata%/Aurora/logs`

**Comment by EdwardChamberlain** [comment]
`16/09/2017 21:14:34: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script)
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor()
16/09/2017 21:14:34: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script)
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor()
[INFO] 16/09/2017 21:14:34: Loading Configuration
[INFO] 16/09/2017 21:14:35: Loading Plugins
[ERROR] 16/09/2017 21:14:36: System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Program Files\Aurora\Plugins\Plugin-Example.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Program Files\Aurora\Plugins\Plugin-Example.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Aurora.Settings.PluginManager.LoadPlugins()


[INFO] 16/09/2017 21:14:36: Loading KB Layouts
[INFO] 16/09/2017 21:14:36: Loading Input Hooking
[INFO] 16/09/2017 21:14:36: Loading Applications
[INFO] 16/09/2017 21:14:39: Loading Device Manager
[INFO] 16/09/2017 21:14:39: Device, Logitech, was initialized
[ERROR] 16/09/2017 21:14:40: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 16/09/2017 21:14:40: Device, Corsair, was not initialized
[ERROR] 16/09/2017 21:14:40: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize()
[INFO] 16/09/2017 21:14:40: Device, Razer, was not initialized
[ERROR] 16/09/2017 21:14:40: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize()
[INFO] 16/09/2017 21:14:40: Device, Clevo Keyboard, was not initialized
[INFO] 16/09/2017 21:15:01: Device, Cooler Master, was initialized
[INFO] 16/09/2017 21:15:01: Device, AtmoOrb, was initialized
[ERROR] 16/09/2017 21:15:01: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID)
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize()
[INFO] 16/09/2017 21:15:01: Device, SteelSeries, was not initialized
[INFO] 16/09/2017 21:15:01: Retrying Device Initialization
[INFO] 16/09/2017 21:15:01: Starting GameStateListener
[ERROR] 16/09/2017 21:15:01: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 16/09/2017 21:15:01: Device, Corsair, was not initialized
[ERROR] 16/09/2017 21:15:01: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize()
[INFO] 16/09/2017 21:15:01: Device, Razer, was not initialized
[ERROR] 16/09/2017 21:15:01: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize()
[INFO] 16/09/2017 21:15:01: Device, Clevo Keyboard, was not initialized
[ERROR] 16/09/2017 21:15:01: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID)
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize()
[INFO] 16/09/2017 21:15:01: Device, SteelSeries, was not initialized
16/09/2017 21:15:01: [IPCServer] Pipe created 2348279
16/09/2017 21:15:01: Listening for game integration calls...
16/09/2017 21:15:01: Loading WinApp...
16/09/2017 21:15:01: [AuroraCommandsServerIPC] Pipe created 61669314
16/09/2017 21:15:01: Loaded WinApp
16/09/2017 21:15:01: Loading ResourceDictionaries...
16/09/2017 21:15:01: Loaded ResourceDictionaries
16/09/2017 21:15:01: Loading ConfigUI...
[INFO] 16/09/2017 21:15:06: Retrying Device Initialization
[ERROR] 16/09/2017 21:15:06: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 16/09/2017 21:15:06: Device, Corsair, was not initialized
[ERROR] 16/09/2017 21:15:06: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize()
[INFO] 16/09/2017 21:15:06: Device, Razer, was not initialized
[ERROR] 16/09/2017 21:15:06: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize()
[INFO] 16/09/2017 21:15:06: Device, Clevo Keyboard, was not initialized
[ERROR] 16/09/2017 21:15:06: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID)
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize()
[INFO] 16/09/2017 21:15:06: Device, SteelSeries, was not initialized
[INFO] 16/09/2017 21:15:11: Retrying Device Initialization
[ERROR] 16/09/2017 21:15:11: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 16/09/2017 21:15:11: Device, Corsair, was not initialized
[ERROR] 16/09/2017 21:15:11: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize()
[INFO] 16/09/2017 21:15:11: Device, Razer, was not initialized
[ERROR] 16/09/2017 21:15:11: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize()
[INFO] 16/09/2017 21:15:11: Device, Clevo Keyboard, was not initialized
[INFO] 16/09/2017 21:15:11: Device, SteelSeries, was not initialized
[ERROR] 16/09/2017 21:15:11: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID)
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize()
[INFO] 16/09/2017 21:15:16: Retrying Device Initialization
[INFO] 16/09/2017 21:15:16: Device, Corsair, was not initialized
[ERROR] 16/09/2017 21:15:16: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[ERROR] 16/09/2017 21:15:16: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize()
[INFO] 16/09/2017 21:15:16: Device, Razer, was not initialized
[ERROR] 16/09/2017 21:15:16: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize()
[INFO] 16/09/2017 21:15:16: Device, Clevo Keyboard, was not initialized
[ERROR] 16/09/2017 21:15:16: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID)
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize()
[INFO] 16/09/2017 21:15:16: Device, SteelSeries, was not initialized
[INFO] 16/09/2017 21:15:21: Retrying Device Initialization
[ERROR] 16/09/2017 21:15:21: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 16/09/2017 21:15:21: Device, Corsair, was not initialized
[ERROR] 16/09/2017 21:15:21: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize()
[INFO] 16/09/2017 21:15:21: Device, Razer, was not initialized
[ERROR] 16/09/2017 21:15:21: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize()
[INFO] 16/09/2017 21:15:21: Device, Clevo Keyboard, was not initialized
[ERROR] 16/09/2017 21:15:21: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID)
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize()
[INFO] 16/09/2017 21:15:21: Device, SteelSeries, was not initialized
[INFO] 16/09/2017 21:15:26: Retrying Device Initialization
[ERROR] 16/09/2017 21:15:26: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 16/09/2017 21:15:26: Device, Corsair, was not initialized
[ERROR] 16/09/2017 21:15:26: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize()
[INFO] 16/09/2017 21:15:26: Device, Razer, was not initialized
[ERROR] 16/09/2017 21:15:26: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize()
[INFO] 16/09/2017 21:15:26: Device, Clevo Keyboard, was not initialized
[ERROR] 16/09/2017 21:15:26: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID)
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize()
[INFO] 16/09/2017 21:15:26: Device, SteelSeries, was not initialized
[INFO] 16/09/2017 21:15:31: Retrying Device Initialization
[ERROR] 16/09/2017 21:15:31: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 16/09/2017 21:15:31: Device, Corsair, was not initialized
[ERROR] 16/09/2017 21:15:31: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize()
[INFO] 16/09/2017 21:15:31: Device, Razer, was not initialized
[ERROR] 16/09/2017 21:15:31: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize()
[INFO] 16/09/2017 21:15:31: Device, Clevo Keyboard, was not initialized
[ERROR] 16/09/2017 21:15:31: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID)
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize()
[INFO] 16/09/2017 21:15:31: Device, SteelSeries, was not initialized
[INFO] 16/09/2017 21:15:36: Retrying Device Initialization
[ERROR] 16/09/2017 21:15:36: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 16/09/2017 21:15:36: Device, Corsair, was not initialized
[ERROR] 16/09/2017 21:15:36: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize()
[INFO] 16/09/2017 21:15:36: Device, Razer, was not initialized
[ERROR] 16/09/2017 21:15:36: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize()
[INFO] 16/09/2017 21:15:36: Device, Clevo Keyboard, was not initialized
[ERROR] 16/09/2017 21:15:36: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID)
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize()
[INFO] 16/09/2017 21:15:36: Device, SteelSeries, was not initialized
[INFO] 16/09/2017 21:15:41: Retrying Device Initialization
[ERROR] 16/09/2017 21:15:41: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 16/09/2017 21:15:41: Device, Corsair, was not initialized
[ERROR] 16/09/2017 21:15:41: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize()
[INFO] 16/09/2017 21:15:41: Device, Razer, was not initialized
[ERROR] 16/09/2017 21:15:41: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize()
[INFO] 16/09/2017 21:15:41: Device, Clevo Keyboard, was not initialized
[ERROR] 16/09/2017 21:15:41: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID)
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize()
[INFO] 16/09/2017 21:15:41: Device, SteelSeries, was not initialized
[INFO] 16/09/2017 21:15:46: Retrying Device Initialization
[ERROR] 16/09/2017 21:15:46: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 16/09/2017 21:15:46: Device, Corsair, was not initialized
[ERROR] 16/09/2017 21:15:46: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize()
[INFO] 16/09/2017 21:15:46: Device, Razer, was not initialized
[ERROR] 16/09/2017 21:15:46: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize()
[INFO] 16/09/2017 21:15:46: Device, Clevo Keyboard, was not initialized
[INFO] 16/09/2017 21:15:46: Device, SteelSeries, was not initialized
[ERROR] 16/09/2017 21:15:46: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID)
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize()
[INFO] 16/09/2017 21:15:51: Retrying Device Initialization
[ERROR] 16/09/2017 21:15:51: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 16/09/2017 21:15:51: Device, Corsair, was not initialized
[ERROR] 16/09/2017 21:15:51: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize()
[INFO] 16/09/2017 21:15:51: Device, Razer, was not initialized
[ERROR] 16/09/2017 21:15:51: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize()
[INFO] 16/09/2017 21:15:51: Device, Clevo Keyboard, was not initialized
[ERROR] 16/09/2017 21:15:51: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID)
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize()
[INFO] 16/09/2017 21:15:51: Device, SteelSeries, was not initialized
[INFO] 16/09/2017 21:15:56: Retrying Device Initialization
[ERROR] 16/09/2017 21:15:56: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 16/09/2017 21:15:56: Device, Corsair, was not initialized
[ERROR] 16/09/2017 21:15:56: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize()
[INFO] 16/09/2017 21:15:56: Device, Razer, was not initialized
[ERROR] 16/09/2017 21:15:56: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize()
[INFO] 16/09/2017 21:15:56: Device, Clevo Keyboard, was not initialized
[ERROR] 16/09/2017 21:15:56: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID)
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize()
[INFO] 16/09/2017 21:15:56: Device, SteelSeries, was not initialized
[INFO] 16/09/2017 21:15:58: Device, Logitech, was shutdown
[INFO] 16/09/2017 21:15:58: Device, Cooler Master, was shutdown
[INFO] 16/09/2017 21:15:58: Device, AtmoOrb, was shutdown
`

**Comment by brainbug89** [comment]
> Bit Messy but see below. (is there a better way to share this?)

For long logs you can use http://pastebin.com/ :wink: 


There are two errors in your log like:

`An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements`

`[ERROR] 16/09/2017 21:14:36: System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Program Files\Aurora\Plugins\Plugin-Example.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)`

The others log fine. Maybe @simon-wh can help with these errors?

**Comment by nmarrufo** [comment]
I have a Pro M RGB and I can't get any lighting effects to show up. I just started trying to understand aurora but is there anything I need to do to control lighting like turning it on or off with certain keypresses or is it just not working with pro m rgb at the moment?

**Comment by simon-wh** [comment]
@nmarrufo If you go to Settings -> Device Manager does it show that it is connected to Cooler Master?

**Comment by nmarrufo** [comment]
It actually shows both a masterkeys pro l first then my pro m and then if I try to reinitialize it will just double the list.

**Comment by simon-wh** [comment]
@nmarrufo What Aurora version are you running right now? If you're not on the [latest dev version](https://github.com/antonpup/Aurora/releases) could you try it and see if it makes a difference?

**Comment by nmarrufo** [comment]
I am on that Dev 3 update atm

**Comment by nmarrufo** [comment]
Whatever was the latest as of yesterday when I got the keyboard.

**Comment by simon-wh** [comment]
@nmarrufo Could you try [v0.6.1-dev4](https://github.com/antonpup/Aurora/releases) that I just put up?

**Comment by nmarrufo** [comment]
Alright so this got lighting FX to work but now my enter key will not light up. I don't think its the keyboard as when i just run the built in lighting fx it will work but with Aurora it will not. Weird I know. Thank you so much for your continued help btw!

**Comment by simon-wh** [comment]
@nmarrufo Could you try [this build](https://ci.appveyor.com/project/antonpup/aurora/build/artifacts)?

**Pull request merged**
