### PR TITLE
Improve Unified HID device

### PR DESCRIPTION
**Pull request by MatrixDJ96**
Hi Aurora Teams,

I have done some changes in Unified HID devices.

**This pull request proposes the following changes:**
- Fix Asus Pugio bottom led
- Update HID libray
- Add update interval settings in ms
- Add shutdown color (with enable/disable option)
- Optimized CPU usage (set led only when necessary)
- Code cleaned up (and refactor)

**Known issues/To do:**
- Nothing!

Those changes should be merged with pr #2220 to enable shutdown color effect on Aurora closing

### CODE REVIEW

**Comment by snake-4** [comment]
Looks okay but I don't see how the update interval setting is useful especially when the default value is 25ms as the Aurora updates at 30FPS anyways.

**Comment by MatrixDJ96** [comment]
> 
> 
> Looks okay but I don't see how the update interval setting is useful especially when the default value is 25ms as the Aurora updates at 30FPS anyways.

I've added the refresh interval option because hidlibray has high CPU usage.
This option allow user to set a slower led update to "fix" this problem

(The 25ms are added to "30FPS" interval)

UPDATE: I've changed default interval to 0ms
UPDATE 2: I've added also shutdown color settings

**Comment by snake-4** [comment]
I feel like shutdown color setting is a bit unnecessary and can be hard-coded to be black instead or at least it can be device specific like the enable setting.

**Comment by MatrixDJ96** [comment]
I could add option to enable/disable shutdown color if for you is "a bit unnecessary" but no hardcoded color, let user decide

UPDATE: I've added option to enable or disable shutdown color

**Comment by MatrixDJ96** [comment]
@diogotr7 @SnakePin this pr is ready for review!

**Pull request closed without merging**
