### PR TITLE
Steelseries Rival 600 and MSI MPG27CQ

### PR DESCRIPTION
**Pull request by wolfcomp**
Expands the Steelseries DeviceManager to support 8 and 103 zones and cleans it up to allow for adding new devices easier

Closes: #1785 
Closes: #1758 
Closes: #1199

### CODE REVIEW

**Comment by wolfcomp** [comment]
Still need to add the json files for Rival 600 and MSI MPG27CQ/MPG27C but all c# code should be working as intended

**Comment by xQwexx** [comment]
I think this closes #1199 Issue as well

**Comment by wolfcomp** [comment]
you would be correct

**Comment by VeraxonHD** [comment]
Any updates/timescale for this being moved into a build? It's making me sad knowing my beautiful Rival 650 is sat here, out of sync :(

**Comment by wolfcomp** [comment]
Until there is a rewrite of how device key id's are redone im not going to continue working on this since it requires to many new integers to be set

**Pull request closed without merging**
