### PR TITLE
Layer performance enhancement and animation update increase 

### PR DESCRIPTION
**Pull request by Aytackydln**
includes changes on #2343 

Since I wasn't planning to contribute I didn't seperate my work between different pull requests. Maybe changse can be reviewed and pull requests can be made seperately

### CODE REVIEW

**Comment by ghost** [comment]
Did this fix the bug where if your aurora been on for a while and your computer been to hibernation mode then you cannot open the GUI again?

**Comment by Aytackydln** [comment]
Probably not. I sometimes get hang ups too

**Comment by gigyun2** [comment]
The interactive layer doesn't work with my ASUS Strix Scope NX

**Comment by Aytackydln** [comment]
Yes, interactive layers are broken from optimizations. Need to work on them

**Comment by Aytackydln** [comment]
Fixed interactive layers. Animations might be off now. Previously most were broken in my branch. I would like to receive feedbacks :)

**Comment by Aytackydln** [comment]
Ok, fixed circular animations. Got the gist of how animations are created. Will fix other animations then I will optimize animation blending with track caches.

**Comment by Aytackydln** [comment]
merged @SnakePin's seperate mousepad branch
updated some dota 2 profile code and updated sandking's update animation
added Bloody mouse and Mouse Pad support

**Comment by gigyun2** [comment]
I tested with the same ASUS strix scope nx keyboard, but through openRGB sdk server this time.
It works super smooth! Thank you!

**Comment by Andikyan** [comment]
Здравствуйте , хотел уточнить насчет героя Winter Wyvern․ почему некоторые герои по типу Troll Warlord и Slark их пассивные способности работают под ультимативной способности ,а такие как Anti Mage, Ursa и так далее нет ? разве это не баг? если работают на других персонажах то значит и на этих персонажах должно работать ! спасибо за понимание

**Pull request closed without merging**
