### PR TITLE
Small fixes in ColorSpectrum and PercentEffect.

### PR DESCRIPTION
**Pull request by VoronFX**
**This pull request proposes the following changes:**

- Fix: ```ColorSpectrum.ToLinearGradient``` ignored shift value.
- Fix typo in ```ColorSpectrum.Shift```.
- Fix: piece of last gradient color in PercentEffect sometimes was also drawn in the beginning due to float error.

### CODE REVIEW

**Comment by VoronFX** [comment]
Arrrrgh. These line endings... =_=
I've just counted that project has only 0.0773% of linux style ("\n") line endings. But these 
0.0773% are almost in any file, causing annoying messages about inconsistent line endings and git comparing changes wrong. Maybe we should normalize all of them in repository and/or tune .gitattributes?

**Comment by simon-wh** [comment]
I've added a gitattributes file which will hopefully sort out that issue. Also, thanks for these changes!

**Comment by brainbug89** [comment]
What kind of line endings are we using now? I'm used to linux style, but I can change my settings if necessary.

**Comment by VoronFX** [comment]
Last time I counted that repository mostly has crlf line endings (92.27%). But ```.giattributes``` now has ```* text=auto``` setting, which means that all committing files will be converted to lf line endings if git decides that file contains text. So in future there should no crlf endings left.
Also we should be aware that git can corrupt files if he suddenly decides that some binary file with extension that git doesn't know contains text.
[Here](https://stackoverflow.com/a/38017715) is recommendation to use explicit setting for file extension instead of for all files. 
Decision on which approach should we use I am leaving to @simon-wh .

**Comment by simon-wh** [comment]
@VoronFX I've removed the auto line and I've changed it so that .cs is set to crlf. If most of it is currently crlf then it would make sense to stick with that. Unless there is a significant reason to switch to using unix fully

**Pull request merged**
