### PR TITLE
Add Logitech G203 to mouses

### PR DESCRIPTION
**Pull request by Bluscream**
**List any issues that this PR fixes:** fixes # , etc...

**This pull request proposes the following changes:**

- Adds Logitech G203 to mouses
- 
- 

**Known issues/To do:**

- 
- 
-

### CODE REVIEW

**Comment by diogotr7** [comment]
This PR just adds an option, no layout / image. If you intend to update this, reopen / submit a new PR.

Also, i think the mouse works fine with other options.

**Comment by Bluscream** [comment]
It works in a weird way currently where it cant be controlled independently

**Comment by diogotr7** [comment]
That's true, but this still isn't fixed with the pull request. This is the type of stuiiff i'll be fixing in my device-dll branch in the near future. I got 2 zones to light on my g900 and g502, doing the same for a g203 shouldn't be difficult at all.

**Comment by Bluscream** [comment]
Can you ping me on discord when it's in alpha stage?

**Pull request closed without merging**
