### PR TITLE
Added CyberpowerPC Tracer III keyboard backlight configs

### PR DESCRIPTION
**Pull request by TrueLecter**
**This pull request proposes the following changes:**

- Add CyberpowerPC Tracer III laptop keyboard layout and device

**Known issues/To do:**

- Set constant keyboard refresh rate to most effective (needs to be measured yet), because keyboard controller does weird things when keyboard is refreshed too frequently

### CODE REVIEW

**Comment by diogotr7** [comment]
The class names feel very familiar to me from a decompiled laptop control center application. May i ask where you got the dll you use?

**Comment by TrueLecter** [comment]
I decompiled Control Center app and removed most of the unused code for other keyboards and backlight types (4 color, etc). The only things left are interaction with keyboard controller using control center method, color adjustment and few other util things

**Comment by diogotr7** [comment]
I am doing a similar thing but because I don't have the hardware it's taking me a while. Here: https://github.com/diogotr7/TongFangRGB

If you could test that it works and is the same hardware that would be nice. Does yours handle the different keyboard layouts? Have you noticed any flickering or other weirdness?

**Comment by TrueLecter** [comment]
Yeah, bottom rows flicker on high refresh rates of all rows. Refreshing only 3-4 at a time is working fine.

**Comment by TrueLecter** [comment]
Now thinking to remove dll completely and change it to your code as it is much smaller

**Comment by diogotr7** [comment]
I wrote the Aurora part as well, you can find it in my fork. Is your layout iso or ansi? Does it have a numpad? If you want to join our discord it would make it easier to double check all the mappings as I know there are at least 4 different layouts (iso and ansi, numpad and without)

**Comment by TrueLecter** [comment]
If I understood correctly, my layout works better on ANSI, because with ISO there are collon key being added (which I assume should be added in ignore list). For international (which I can test on) it works well

**Comment by TrueLecter** [comment]
Really sorry for such a long delay. I checked your fork on branch feature/tongfang. What is your TongFang.dll? Is it from your TongFangRGB project?

**Comment by diogotr7** [comment]
hey, sorry i'm taking so long to review PR's

Yes, that dll is from my project. This pull is (hopefully) superceded by #1940 , which is tongfang's implementation of this, with official support. If you wish, you can always use this implemnentation, or mine, mbut it won't make it into an official release due to an official one being available.

I'm also not completely sure about which resellers are going to be supported by #1940, but that's not up to me to decide. 

Thanks for controbuting, you just got a bit unlucky since we were in talks with tongfang and resellers to get this supported officially :)

**Comment by TrueLecter** [comment]
I'm actually glad to see that you managed to get official support. Waiting for that branch to release!

**Pull request closed without merging**
