### PR TITLE
Changed the Process detection to WINAPI only.

### PR DESCRIPTION
**Pull request by r3sist3nt**
### Fixes:
#430 
#424

The old Process Detection was using the ProcessModule to get the FilePath. This could cause problems, because games, compiled in x64 can't be accessed in this way.
I changed the detection to only use WINAPI calls, so Aurora don't need to access the Process directly anymore.
### Changes:
I only needed to change the GetActiveWindowsProcessname() Method in GameEventHandler.cs
I'am using the `GetProcessHandleFromHwnd()` call to get the process handle from the foreground window, then i get the full path with the `GetModuleFileNameEx()` call.

No Exception handling is needed, the returned fileName will be an empty string when no foreground window exists.

### CODE REVIEW

**Comment by antonpup** [comment]
Thanks for the fixup. I am confused as to why the old method doesn't work properly? Do you have a more detailed explanation for that? Also, Does this allow Aurora (if not run as admin) to retrieve the name of a process running as admin?

**Comment by r3sist3nt** [comment]
I was running into the problem when i tried to creating a custom profile for Rust. Ich tried everything, but ist just doesn't want to work.
The game itself was running with user privilige all time, while Aurora was running as Admin. I debbuged the output, and there was a Win32Exception all the time rust was in the foreground. I can post the logs later, but the documentation said windows ist throwing this exception when a 32 bit applikation

**Comment by r3sist3nt** [comment]
I attached the logs of my and your branch. I added two logging lines to the original code in the `GetActiveWindowsProcessname()` to fetch the exception and the detected application path.
Have a look at line 86-101, that was the time Rust was open. It makes no difference if aurora is run as admin or not, the exception stays the same.
After my change, no more exception is thrown and RustClient.exe is recognized without any problems, see line 86-89 in debug_newcode.txt
Atleast when both processes run with the same privilige.
The Aurora-user, Rust-admin case does still not work here, but thats a generell privilige problem i think


[debug_oldcode.txt](https://github.com/antonpup/Aurora/files/752933/debug_oldcode.txt)
[debug_newcode.txt](https://github.com/antonpup/Aurora/files/752934/debug_newcode.txt)

**Comment by r3sist3nt** [comment]
I found another bug. I fixed it, but i will test it for some days to be sure everythink is working fine now

**Comment by r3sist3nt** [comment]
I am testing this detection method now for days and there was no false detection of any game i played.

**Comment by antonpup** [comment]
It's not that I don't want to merge it. I was just wondering if it holds any improvements over the current method.

I'll merge it sometime later, for now, education takes priority for me.

**Pull request merged**
