### PR TITLE
G213 Support

### LINKED ISSUE #205: Logitech G213 Support (Zone based keyboard support)
Hey,
I already used to play games with my Orion Spark and Aurora. Now i got a G213 and game implementation isnt working at all. 
Aurora seems to fail to activate certain keys. It can change colour and brightness of the wohle keyboard (like Changing Teams in CS Go, Flash, Burn) but cant adress single keys.

A Bomb Timer for example will be flashing red over the whole keyboard :( Kills, Health Ammo etc. are not shown in general...

EDIT: https://www.youtube.com/watch?v=ptjTAdyskSQ&feature=youtu.be It only responds to the "Mouse/Headset" Field when configuring a profile :(

EDIT: Since one cant light up single keys in the Logitech Gaming Software, im getting the feeling that the G213 is not a real "RGB" Keyboard... (only rainbow effect :/)

### PR DESCRIPTION
**Pull request by SnakePin**
**List any issues that this PR fixes:** 

Fixes #205 

**This pull request proposes the following changes:**

- Adds support for zone-based Logitech G213 keyboard.

**Known issues/To do:**

- Unknown

### CODE REVIEW

**Comment by t0mb3r** [comment]
I have changed the files, what now?

**Comment by t0mb3r** [comment]
I mean how do I build an .exe?
csproj?

**Comment by SnakePin** [comment]
@t0mb3r Uninstall Aurora first, then download this https://ci.appveyor.com/api/buildjobs/6x8vc7y0ag01y0dd/artifacts/Aurora-setup-v0.6.2b-462-muafneen.exe then setup

**Comment by Gurjot95** [comment]
> thank you, it wasnt working because I had a g502 but it wasnt enabled.

Can you let us know if G213 is working good for you now so we can add its support to Aurora?

**Pull request closed without merging**
