### PR TITLE
Fix invalid enumeration exception when desktop disabled

### PR DESCRIPTION
**Pull request by xQwexx**
Fix use case when deleting the device in the foreach loop.

### CODE REVIEW

**Comment by Fluto** [comment]
`asusHandler.DisconnectDevice(this);` should still be called

Every piece in the code that uses a foreach to iterate over the devices should use the lock, and should be a for loop instead. In the case where something may be removed, the for loop should be reversed.

For example 
`Project-Aurora\Devices\Asus\AsusHandler.cs : 181`
```CSharp
foreach (var device in devices)
                    device.Stop();
```
Should be this instead
```CSharp
for (var i = devices.Count - 1; i >= 0; i--)
                    devices[i].Stop();
```

**Comment by xQwexx** [comment]
At first I also thought that the asusHandler.DisconnectDevice(this)
Should be called in the taskcanceledexception but after think it through, this exemption is going to happen if the running thread was cancelled via device.Stop() and every time when this was used it's followed by device deletion and that's all what is the disconnectdevice function is doing (apart from logging)

**Comment by diogotr7** [comment]
It would be awesome if we could get this fixed and merged as it looks like a significant issue.

**Comment by diogotr7** [comment]
#2037 has a couple more fixes so i'll merge that one instead. Thanks for contributing

**Pull request closed without merging**
