### PR TITLE
Minor Overrides System Improvements

### PR DESCRIPTION
**Pull request by Wibble199**
This PR attempts to fix a few issues that have been found with the Overrides System. Current known and fixed bugs are:

* [x] Game State dropdowns that are children of and/or expressions being empty
* [x] ~Changing the overrride logic does not trigger a save and so sometimes you can lose progress if you close Aurora immediately after editing the logic.~ According to [this Discord message](https://discordapp.com/channels/427609830073696258/428606931700023299/554318942823251988), it's not an issue with the overrides system in particular, so skipping it in this override fix PR.
* [x] Add exclude keys/regions to all Layers
* [x] Add all properties to the LayerEffectConfig editor
* [x] Improve audio visualizer support (Add secondary color, etc.)
* [x] Add current/maximum value to percent Layers
* [x] Added a **temporary** `LogicOverrideIgnoreProperty` attribute for layer handlers so specify that one or more of their properties should not be shown in the overridable property list. This should be **temporary** until we are able to resolve the layer handler properties' inheritance, which I recommend is done next time there is a change planned that will likely break existing profiles anyways (such as the device layout rework perhaps?).

### CODE REVIEW

**Comment by gitmacer** [comment]
### here are some more think that should be changed:

Remove Primary/Secondary Color Overwriting for following Layers:
-Gradient Layer
-Gradient Fill Layer
-Image Layer
-Percent (Gradient) Effect Layer
-Glitch Effect Layer
-Animation Layer

Also:
-Script Layer: Remove Primary Color and Affected Keys
-Remove Affected Keys from Fill Layers
-Add Exclude Keys/Regions to all Layers
-Add Gradient overwriting to Percent (Gradient) Effect Layer 
-Gradient logic (LayerEffectConfig) should not overwride other variables(Effect Speed... should also be overwritable)
-Improve Audio Visualizer support (no secondary Color...)

Effect Layers:
-Add Current/Maximum Value

**Comment by Wibble199** [comment]
The reason that many layers have additional properties is because the layer handler properties inherit from the `LayerHandlerProperties2Color` class which is exposing the primary/secondary properties. While would be possible with some layers to remove this relationship and inherit from the `LayerHandlerProperties` class instead, there are many layers that use this directly (rather than creating their own properties and extending) which means that changing the names or types of the property classes will **break existing profiles**. If there is ever a release planned that will knowingly break profiles for other reasons then I will consider tidying up this, however I think it currently does not warrant breaking profiles for the sake of a few properties being present when they shouldn't be.

**Comment by gitmacer** [comment]
ok, but If it is not possible to easily remove these properties it should still be possible to fix following things:

-Add Exclude Keys/Regions to all Layers
-Add Gradient overwriting to Percent (Gradient) Effect Layer
-Gradient logic (LayerEffectConfig) should not overwride other variables(Effect Speed... should also be overwritable)
-Improve Audio Visualizer support (no secondary Color,...)

Effect Layers:
-Add Current/Maximum Value

**Comment by gitmacer** [comment]
Freestyle selection is affecting others when at the same position. https://cdn.discordapp.com/attachments/428606931700023299/564876515037151235/freestyle_bug.gif

**Comment by gitmacer** [comment]
Ok this bug is not related to this pr, because the Skype overlay has the same bug.

**Pull request merged**
