### PR TITLE
Corsair and Asus Support via RGB.NET

### PR DESCRIPTION
**Pull request by Gurjot95**
Experimental Corsair and Asus Support using RGB.NET. Using RGB.NET from now on will be as easy to add new devices as adding 3 lines of codes. Technically, all devices supported by RGB.NET can be supported by Aurora now.

Please test this PR for different corsair and asus peripherals such as Light Strips, RAM, Cooler etc.

### CODE REVIEW

**Comment by maestroraymond** [comment]
How do I test this?

**Comment by Gurjot95** [comment]
You can go to Appveyor link: https://ci.appveyor.com/project/Gurjot95/aurora/builds/24973101/artifacts

**Comment by copystring** [comment]
Works for me with my asus rog maximus x hero, corsair vengence rgb ram, corsair h100i pro watercooler, asus 2080ti strix.
It takes the color from the mouse right? I assume for more ways to configure the rewrite of aurora is needed.

**Comment by caw1** [comment]
cant get into share modus // or am i just blind ? can u tell me where i can controll my MM800 via Aurora and my LL140 via iCue? sorry for that dumb question :)

**Comment by caw1** [comment]
please can you please help me? i got a MM800 mousepad and 2x LL140 fans. i want to control the mousepad via aurora constantly and the fans by icue. is that possible?

**Comment by Gurjot95** [comment]
Hey, I need to add shared mode option in device manager but it should be possible in future builds.

**Comment by BenjaminHoegh** [comment]
> Experimental Corsair and Asus Support using RGB.NET. Using RGB.NET from now on will be as easy to add new devices as adding 3 lines of codes. Technically, all devices supported by RGB.NET can be supported by Aurora now.
> Please test this PR for different corsair and asus peripherals such as Light Strips, RAM, Cooler etc.

Where  do you find the keyboard layout files?

**Comment by jizichun** [comment]
Works for me except for the new rgb pump and res combo (XD5) It is hooked up to a command pro hub and doesn't seem to work :C

**Comment by zejjnt** [comment]
Yay, 124 made all the lights work again!

**Pull request merged**
