### PR TITLE
Support for SoundBlasterX VanguardK08

### LINKED ISSUE #1235: Support for Vanguard K08
Will this keyboard get support?
It has an SDK (Aurora Reactive)

### PR DESCRIPTION
**Pull request by rajkosto**
Fixes #1235 

TODO: Test mouse support
~~TODO: Tweak it a bit to support non-US versions of the VanguardK08~~

### CODE REVIEW

**Comment by Gurjot95** [comment]
Can you post this on PR instead? It's not an issue, but a Pull Request

**Comment by simon-wh** [comment]
Would you consider this PR ready to merge? I'm currently finalising the current version for the next Aurora release

**Comment by simon-wh** [comment]
Thank you very much for your contribution!

**Comment by boJob-1** [comment]
I have the SoundBlasterX siege m04 but no suported rgb keyboard, how do I set aurora up to work with it and what do I need to do to get the information you need to fix possible problems?

**Pull request merged**
