### PR TITLE
Asus aura support

### PR DESCRIPTION
**Pull request by Fluto**
Test Asus build with support for AuraSDK v3

**List any issues that this PR fixes:**
Fixes: #546 

**This pull request proposes the following changes:**
- Add a new device `Asus`, this aims to support all devices that falls under the AuraSDK
- Modifies Strix Flare device to have more LEDs to be accessed

**Known issues/To do:**

- Test Test Test!
- Link to an Asus driver installer

### CODE REVIEW

**Comment by vicdilou** [comment]
Hello,
thanks it works great !
But the light is sync with my mouse, can I add another just for aura or sync with another key ?
Thank you

**Comment by kekkokk** [comment]
I've compiled the source of this branch and it loaded the first time.
next step was going to device and select preferred keyboard Strix Flare.
Then when I tried to change the preferred language into Italian it crashed and I'm not able to start it again. 

aurora_debug

Tried also to delete the build folder. can you give me some hint of where it stores the settings so I can clear and start from scratch to be able to reproduce the issue?
Maybe I can help testing with my Claymore.
Also, can you provide me the link of the latest Asus SDK I have to install?

I did a previous integration of my claymore and it works great (only problem I had to compile only in x86 since the dlls were x86)

I know about nothing of windows programming and C#, I'm more a nodejs / c++ dev, but maybe I can help testing

Thanks

**Comment by kekkokk** [comment]
Hey! Asus Claymore owner here!

I get this error: Exception thrown: 'System.InvalidCastException' in Aurora.exe

when doing this cast: 
err_1

**Comment by kekkokk** [comment]
https://github.com/kekkokk/Aurora/tree/asus-aura-support

Started integrating support for ROG Claymore keyboard which seems to be a bit different (Its recognised as a keyboard but if you try to cast to keyboard the program explodes).

I noticed that in async mode, when pressing lots of keys the app crashes saying "the connection with the mainboard was lost" but the keyboard keys are super responsive. (I have a strix mb with rgb ram and strix VGA so I'm testing everything).

In not async mode it worked without a single crash but the keyboard response time is much higher. I can see the visual feedback lag when I press a key.

Let me know what do you think

That first claymore integration is with the numpad on the right only. (since it can be swapped).

**Comment by kekkokk** [comment]
I keep getting AccessViolationException in the foreach Device.Lights
Is this happening to you too?

**Comment by Fluto** [comment]
@kekkokk 
Hey, I don't have too much time to look into the Claymore issue :(. AccessViolationException seems to be happening internally from the API. I'm not sure how to keep it from complaining. I'm waiting for Asus to expose more of the API or release a nice update. (Or till I have more time to investigate)

**Comment by kekkokk** [comment]
Claymore is not a problem anymore, I wrapped it in it's own object. The access violation exceptions occurs only when threaded so It might be a concurrency issue.I think the only solution here is to wait for each device until it has applied the colors and skip the job if another update comes when busy during apply. I'm looking into it. seems to happen also in RGB.net which is the new implementation in the dev branch. At the moment seems that the bottleneck is the Vga (asus strix 1080) which takes up to 57 ms to apply. another interesting thing is that I made a little project which applies the colors every 33 ms (30fps) at every device and it works perfectly.

[Playground](https://github.com/kekkokk/aura_csharp_playground)

The same code applied in aurora is quite laggy, so I need to study how threads are handled inside aurora (again, I'm new in c#)

Hope to find a reliable solution

**Comment by Fluto** [comment]
(I don't have github email enabled for some reason, so I didn't see your reply)
My threaded approach should be waiting per device, but not for all devices. Which is an interesting idea. I have a Pugio Mouse which decides to deadlock internally and make each call 3seconds long, which is why I made the async approach...

**Pull request closed without merging**
