### PR TITLE
Add SteelSeries Apex M750 and M750 TKL

### PR DESCRIPTION
**Pull request by FHeilmann**
**This pull request proposes the following changes:**

- Add SteelSeries Apex M750
- Add SteelSeries Apex M750 TKL (Ten Key Less)
- Rename some files reused between SS keyboards

**Known issues/To do:**

- Only Keyboards for now, will add mice soon

### CODE REVIEW

**Comment by brainbug89** [comment]
Could you test it with an Apex M750?

**Comment by FHeilmann** [comment]
I have a M750 that I used to make these changes. I kept tweaking the layout files of the M800 until my US layout M750 seemed to work without issue. Then I just grep'd the code base for the M800 and replicated the code for the M750.

For the TKL I went with the online press material. The M750 TKL replaces the right WIN key with the SS logo key, contrary to the M750, where the right APP key is replaced by the SS logo key. 

As I said, the modified M800 layout was working with my M750, but I couldn't compile in the changes yesterday due to some issue with nuget. If you want you can hold off on merging this until I can compile again and test the layout in a non-hacky way.

**Comment by FHeilmann** [comment]
The TKL had to be fixed, didn't now that I have to add the linebreaks manually.
I fixed it up and squashed all the commits. It works with my M750 and I'm 99% certain the M750 TKL works as well (as far as I can tell using my M750) 

From my side this is ready to merge.

**Comment by FHeilmann** [comment]
Anything else you want me to fix? Otherwise I'll probably start adding Steelseries mice to this PR sometime next week.

**Comment by brainbug89** [comment]
Nice. :+1:  I think @simon-wh will merge it as soon as he has the time. :wink:

**Comment by simon-wh** [comment]
Thanks for the contribution!

**Pull request merged**
