### PR TITLE
Dota Effects WIP

### PR DESCRIPTION
**Pull request by JoniSykes**

### CODE REVIEW

**Comment by antonpup** [comment]
Please make pull requests to the dev branch, not master.

**Comment by JoniSykes** [comment]
As soon as I figure out how to do that, I will swap it over. :)

**Comment by JoniSykes** [comment]
There we go. Thanks.

**Comment by antonpup** [comment]
Also, you have removed a historic monument in honor of the darker times.

https://github.com/antonpup/Aurora/pull/380/files#diff-612a51fdf5ac8a0277272fb6b1c9438bL600

Pls. Is just a harmless comment!

**Comment by JoniSykes** [comment]
Don't fret over the switch/case, I'll be turning this into a factory pattern for performance.

**Comment by JoniSykes** [comment]
@antonpup Are you available to look over this PR? Most of the changes so far have been performance refactors which aren't finished yet. I still have one switch/case to adapt into a dictionary.
Other than that I've added some Morphling effects too.
How feasible is it to add an itemEffectLayer do you think? For item casting?
Thanks!

**Comment by antonpup** [comment]
One more thing to warn you. I was going to eventually add more options to the Ability layer (and presumably the item layer). The original plan was to allow for color customization, so the user can select a green Razor Plasma Field instead of default blue, etc. And then once I added an animation editor, to allow users to edit the animations.

The animation editor is a while ways away, but color settings can be added anytime ;) So... If you would be so kind, as to put all colors into layer's properties? And then make a Grid inside a ScrollViewer to place all the color controls in. So user can scroll through the billions of colors they want to change.

**Comment by JoniSykes** [comment]
@antonpup That sounds fantastic! I'll do my best to do that for you.
While you're here I have another question. What am I missing in the logic that is stopping certain effect combinations from working.
I'll give you an example:
I added an effect for Legion Commander's Duel. If I just cast duel, I see the effect working fine.
If I cast press the attack first, a spell currently with no effect, then cast duel immediately after (this is common in Dota2 matches) then I don't see the duel effect.
Any ideas?

**Comment by JoniSykes** [comment]
@antonpup I can see some colours in Dota2Settings.cs is that where you meant?
Or is this new functionality you're after?

**Comment by antonpup** [comment]
On second thought, don't bother with it. If I ever make an animation editor, the colors will be inside the animation. So.. no need to waste a bunch of variables.

**Comment by JoniSykes** [comment]
Sure that sounds better. Ok boss. How do you like the PR so far?

**Comment by antonpup** [comment]
I haven't looked yet. After I saw a commit that changed every animation definition. I kinda just said to myself, "I will just dedicate a day sometime to look over this carefully". That day hasn't come yet.

**Comment by JoniSykes** [comment]
Yeah I think that was my formatting preferences....soz.

**Comment by JoniSykes** [comment]
Hi @antonpup.
I can't see anything about abilities with charges instead of cooldowns. Any info that might be useful?
It's not even part of the Ability Node. I can see that items have charges, but maybe the GS doesn't show ability charges.
Any help would be awesome.
Joni

**Comment by antonpup** [comment]
Last time I checked my GSI Library for Dota 2, such information wasn't exposed. I can take a look again, but I doubt it's visible.

On a side note, I just started working on an animations editor. It's not functional just yet, but foundation is there. :)

**Comment by JoniSykes** [comment]
@antonpup That's awesome! Exciting stuff!
Have you had a look at the dictionary I'm using in my PR to avoid the if/else block. It's more performant. 
Only mentioning in case it impacts your editor.
Cheers.

**Comment by antonpup** [comment]
Editor will work with a provided Animation Mix, so whatever the format, as long as it's an AnimationMix, it should work.

**Comment by antonpup** [comment]
Before I merge your commit, I will be slightly reworking the way AnimationTracks work. So they can have random generation and connect to previous line end inside. Which will affect some effects in Dota 2 that involve generation (like laguna blade).

Once that is fixed up, I will merge the pr. I will make another comment here once I have committed the changes I mentioned above.

**Comment by JoniSykes** [comment]
Hi again @antonpup :)
I've been pretty quiet on here for a while. How's it going your end? Need any help?

**Comment by antonpup** [comment]
I've been doing other things such as school, and profile imports. I do have a fairly functional animation editor (even made an animation layer) on the profile-import branch. I haven't done the promised random generation and connecting to previous lines.

I did clean up the repository root on dev, by moving the project into "Project-Aurora" folder. So that made your pr conflict with the branch. If you can fix that up, I'll accept the PR and develop further with it.

**Comment by JoniSykes** [comment]
Will do. I'll clean it up by the end of next week. I may have questions as I go, but I'll cross that bridge later.

**Comment by antonpup** [comment]
Ok. I know I am super late, but i wanted to bump this to see if you are willing to make the code mergeable. I am looking to release a new update sometime before June, so I want to include as much as possible.

**Comment by JoniSykes** [comment]
Yeah....I've not had any time recently. I'll try my best though.

**Comment by juanj** [comment]
Hey @JoniSykes any chances you can finish this?
Maybe I can help if you don't have time...

**Comment by C-Kenny** [comment]
Would love these effects in the main release.

**Pull request closed without merging**
